//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Davisoft_BDSProject.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDSPersonalInformationEn
    {
        public int ID { get; set; }
        public int IdAccount { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public System.DateTime Birthday { get; set; }
        public int Sex { get; set; }
        public int MaritalStatus { get; set; }
        public Nullable<int> Province { get; set; }
        public string PermanentAddress { get; set; }
        public string TemporaryAddress { get; set; }
        public string Description { get; set; }
        public string UrlImage { get; set; }
        public Nullable<int> UrlImageCheck { get; set; }
        public string KeySearch { get; set; }
        public int Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public Nullable<System.DateTime> DateReup { get; set; }
        public Nullable<int> CountReup { get; set; }
        public Nullable<int> MaxReup { get; set; }
    }
}
