//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Davisoft_BDSProject.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bdspersonalinformation
    {
        public int Id { get; set; }
        public Nullable<int> IdAccount { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> Sex { get; set; }
        public string Address { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> District { get; set; }
        public string FullAddress { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> Experience { get; set; }
        public Nullable<int> ProfessionalExperience { get; set; }
        public Nullable<int> Education { get; set; }
        public Nullable<int> IdLoaiNghe { get; set; }
        public string Description { get; set; }
        public string UrlImage { get; set; }
        public string KeySearch { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
    }
}
