//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Davisoft_BDSProject.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDSPerNewEn
    {
        public int ID { get; set; }
        public string TitleProfile { get; set; }
        public Nullable<int> CareerProfile { get; set; }
        public Nullable<int> ProvinceProfile { get; set; }
        public Nullable<int> SalaryProfile { get; set; }
        public Nullable<int> EducationProfile { get; set; }
        public Nullable<int> ExperienceProfile { get; set; }
        public Nullable<int> LanguageProfile { get; set; }
        public Nullable<int> LevelProfile { get; set; }
        public string CareerGoalProfile { get; set; }
        public Nullable<int> MSWordOffice { get; set; }
        public Nullable<int> MSExcelOffice { get; set; }
        public Nullable<int> MSPowerPointOffice { get; set; }
        public Nullable<int> OutlookOffice { get; set; }
        public string OrderOffice { get; set; }
        public string Skills { get; set; }
        public string Hobby { get; set; }
        public Nullable<int> SearchCheck { get; set; }
        public string KeySearch { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public Nullable<int> PerId { get; set; }
        public string FileUrl { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
