//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Davisoft_BDSProject.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public string countryCode { get; set; }
        public int name_id { get; set; }
        public string languages { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
