//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Davisoft_BDSProject.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BDSApply> BDSApplies { get; set; }
        public DbSet<BDSEmper> BDSEmpers { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<CountryText> CountryTexts { get; set; }
        public DbSet<District> Districts { get; set; }
        public DbSet<DistrictText> DistrictTexts { get; set; }
        public DbSet<Location> Locations { get; set; }
        public DbSet<LocationText> LocationTexts { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<StateText> StateTexts { get; set; }
        public DbSet<BDSNews_Career> BDSNews_Career { get; set; }
    }
}
