//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Davisoft_BDSProject.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        public int location_id { get; set; }
        public string countryCode { get; set; }
        public int state_id { get; set; }
        public Nullable<int> district_id { get; set; }
        public int name_id { get; set; }
        public string zipCode { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public bool preferred { get; set; }
        public string polygon { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
