//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Davisoft_BDSProject.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class permission
    {
        public permission()
        {
            this.roles = new HashSet<role>();
        }
    
        public int ID { get; set; }
        public string Target { get; set; }
        public string Right { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<role> roles { get; set; }
    }
}
