//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Davisoft_BDSProject.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phuong
    {
        public Nullable<float> ID { get; set; }
        public string WardName { get; set; }
        public Nullable<float> SuburbID { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string polygon { get; set; }
        public string rowguid { get; set; }
    }
}
