//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Davisoft_BDSProject.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public role()
        {
            this.menus = new HashSet<menu>();
            this.permissions = new HashSet<permission>();
            this.users = new HashSet<user>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string RoleLevel_Value { get; set; }
    
        public virtual ICollection<menu> menus { get; set; }
        public virtual ICollection<permission> permissions { get; set; }
        public virtual ICollection<user> users { get; set; }
    }
}
