//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBDS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDSBranch
    {
        public BDSBranch()
        {
            this.BDSTransactions = new HashSet<BDSTransaction>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Phone { get; set; }
        public int IdArea { get; set; }
        public string Description { get; set; }
        public string KeySearch { get; set; }
        public int Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
    
        public virtual BDSArea BDSArea { get; set; }
        public virtual ICollection<BDSTransaction> BDSTransactions { get; set; }
    }
}
