//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBDS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bdsnew
    {
        public int IdAdvert { get; set; }
        public string Title { get; set; }
        public string AddressWork { get; set; }
        public string FromSalary { get; set; }
        public string ToSalary { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Bonus { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<int> Experience { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> IdBranch { get; set; }
        public string DesInfoCompany { get; set; }
        public string DesWork { get; set; }
        public string Benefit { get; set; }
        public Nullable<int> FromAge { get; set; }
        public Nullable<int> ToAge { get; set; }
        public Nullable<int> IdTimeWork { get; set; }
        public string NameCompany { get; set; }
        public string AddressApply { get; set; }
        public string AddressContact { get; set; }
        public string PhoneContact { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> FromDeadlineSubmit { get; set; }
        public Nullable<System.DateTime> toDeadlineSubmit { get; set; }
        public Nullable<int> IdLanguage { get; set; }
        public string WebSiteCompany { get; set; }
        public Nullable<int> IdTypeNews { get; set; }
        public Nullable<System.DateTime> FromCreateNews { get; set; }
        public Nullable<System.DateTime> ToCreateNews { get; set; }
        public Nullable<int> IdAcount { get; set; }
        public Nullable<int> Probatonary { get; set; }
    }
}
