//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBDS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bdsnew
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> AddressWork { get; set; }
        public Nullable<int> FromSalary { get; set; }
        public Nullable<int> ToSalary { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Bonus { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<int> IdTimeWork { get; set; }
        public Nullable<int> IdEducation { get; set; }
        public string Career { get; set; }
        public string DesCompany { get; set; }
        public string DesWork { get; set; }
        public string Benefit { get; set; }
        public Nullable<int> FromAge { get; set; }
        public Nullable<int> ToAge { get; set; }
        public Nullable<int> TimeProbationary { get; set; }
        public string NameCompany { get; set; }
        public string AddressApply { get; set; }
        public string NamesContact { get; set; }
        public string PhoneContact { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> FromDeadline { get; set; }
        public Nullable<System.DateTime> ToDeadline { get; set; }
        public Nullable<int> IdLanguage { get; set; }
        public string WebSiteCompany { get; set; }
        public Nullable<int> IdTypeNews { get; set; }
        public Nullable<System.DateTime> FromCreateNews { get; set; }
        public Nullable<System.DateTime> ToCreateNews { get; set; }
        public Nullable<int> IdAcount { get; set; }
        public string KeySearch { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public Nullable<decimal> MoneyInDay { get; set; }
        public Nullable<decimal> TotalMoney { get; set; }
        public string UrlImage { get; set; }
        public Nullable<int> IdTypeNewsCuurent { get; set; }
        public Nullable<System.DateTime> DateReup { get; set; }
        public Nullable<int> CountReup { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> RefTranHis { get; set; }
    }
}
