//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBDS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDSPersonalInformation
    {
        public int ID { get; set; }
        public int IdAccount { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public System.DateTime Birthday { get; set; }
        public int Sex { get; set; }
        public string Address { get; set; }
        public int City { get; set; }
        public int District { get; set; }
        public string FullAddress { get; set; }
        public int MaritalStatus { get; set; }
        public int Salary { get; set; }
        public int Experience { get; set; }
        public int ProfessionalExperience { get; set; }
        public int Education { get; set; }
        public int IdLoaiNghe { get; set; }
        public string Description { get; set; }
        public string UrlImage { get; set; }
        public string KeySearch { get; set; }
        public int Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
    }
}
