//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBDS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDSPerNews_LangDegrees
    {
        public int ID { get; set; }
        public Nullable<int> ID_BDSPerNews { get; set; }
        public string Name { get; set; }
        public Nullable<int> Language { get; set; }
        public Nullable<int> Listening { get; set; }
        public Nullable<int> Speaking { get; set; }
        public Nullable<int> Reading { get; set; }
        public Nullable<int> Writing { get; set; }
        public string Decription { get; set; }
        public string KeySearch { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
    }
}
