//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBDS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDSTransaction
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string KeySearch { get; set; }
        public int IdAccount { get; set; }
        public Nullable<int> IdBank { get; set; }
        public Nullable<int> IdBranch { get; set; }
        public double Money { get; set; }
        public double MoneyEventAdd { get; set; }
        public double EventDisPercent { get; set; }
        public int Point { get; set; }
        public System.DateTime TranDate { get; set; }
        public int Type { get; set; }
        public Nullable<int> RefTranHis { get; set; }
        public int Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
    }
}
