//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBDS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch
    {
        public branch()
        {
            this.counters = new HashSet<counter>();
            this.users = new HashSet<user>();
            this.users1 = new HashSet<user>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Name2 { get; set; }
        public string Address { get; set; }
        public string AddressEnglish { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string TaxNumber { get; set; }
        public System.DateTime C_Created { get; set; }
        public Nullable<System.DateTime> C_Updated { get; set; }
        public Nullable<System.DateTime> C_Deleted { get; set; }
        public string EntityStatus_Value { get; set; }
    
        public virtual ICollection<counter> counters { get; set; }
        public virtual ICollection<user> users { get; set; }
        public virtual ICollection<user> users1 { get; set; }
    }
}
