//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBDS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class language
    {
        public language()
        {
            this.users = new HashSet<user>();
        }
    
        public int ID { get; set; }
        public string Value { get; set; }
        public string DisplayName { get; set; }
        public string Image { get; set; }
    
        public virtual ICollection<user> users { get; set; }
    }
}
